export const demoConfig = {
  holdMinutes: 10,
  otpTtlMinutes: 5,
  resendCooldownSeconds: 30,
  maxOtpAttempts: 3,
  demoOtp: '123456',
  requireOtpForCurrentNumber: true,
  depositRate: 0.2,
  paymentTiming: 'Pay deposit before appointment starts',
  noteLimit: 200,
  serviceSearchLimit: 10,
  maxBranchResults: 10,
  demoDisclaimer: 'Illustrative demo data — not verified business pricing or availability.',
};

export const branches = [
  {
    id: 'dubai_main',
    countryId: 'AE',
    countryLabel: 'UAE',
    city: 'Dubai',
    region: 'Dubai',
    nameEn: 'GLO365 Dubai',
    nameAr: 'جلوس دبي',
    address: '1094 Al Wasl Road, Dubai',
    timezone: 'Asia/Dubai',
    currency: 'AED',
    latitude: 25.2212,
    longitude: 55.2766,
    hours: { open: '09:00', close: '20:00' },
    demoNote: true,
  },
  {
    id: 'abudhabi_hub',
    countryId: 'AE',
    countryLabel: 'UAE',
    city: 'Abu Dhabi',
    region: 'Abu Dhabi',
    nameEn: 'GLO365 Abu Dhabi',
    nameAr: 'جلوس أبو ظبي',
    address: 'Demo location, Abu Dhabi',
    timezone: 'Asia/Dubai',
    currency: 'AED',
    latitude: 24.4539,
    longitude: 54.3773,
    hours: { open: '10:00', close: '19:00' },
    demoNote: true,
  },
  {
    id: 'riyadh_center',
    countryId: 'SA',
    countryLabel: 'Saudi Arabia',
    city: 'Riyadh',
    region: 'Riyadh',
    nameEn: 'GLO365 Riyadh',
    nameAr: 'جلوس الرياض',
    address: 'Demo address, Riyadh',
    timezone: 'Asia/Riyadh',
    currency: 'SAR',
    latitude: 24.7136,
    longitude: 46.6753,
    hours: { open: '10:00', close: '21:00' },
    demoNote: true,
  },
  {
    id: 'jeddah_beach',
    countryId: 'SA',
    countryLabel: 'Saudi Arabia',
    city: 'Jeddah',
    region: 'Jeddah',
    nameEn: 'GLO365 Jeddah',
    nameAr: 'جلوس جدة',
    address: 'Demo address, Jeddah',
    timezone: 'Asia/Riyadh',
    currency: 'SAR',
    latitude: 21.4858,
    longitude: 39.1925,
    hours: { open: '09:30', close: '20:30' },
    demoNote: true,
  },
  {
    id: 'dubai_downtown',
    countryId: 'AE',
    countryLabel: 'UAE',
    city: 'Dubai',
    region: 'Downtown',
    nameEn: 'GLO365 Downtown',
    nameAr: 'جلوس وسط المدينة',
    address: 'Demo location, Downtown Dubai',
    timezone: 'Asia/Dubai',
    currency: 'AED',
    latitude: 25.2048,
    longitude: 55.2708,
    hours: { open: '09:00', close: '19:30' },
    demoNote: true,
  },
];

export const services = [
  { id: 'lip_blush', branchId: 'dubai_main', category: 'Lips', nameEn: 'Lip Blush', nameAr: 'غنية الشفاه', durationMinutes: 90, price: 800, currency: 'AED' },
  { id: 'brow_lamination', branchId: 'dubai_main', category: 'Brows', nameEn: 'Brow Lamination', nameAr: 'تجعيد الحواجب', durationMinutes: 60, price: 500, currency: 'AED' },
  { id: 'lash_lift', branchId: 'dubai_main', category: 'Lashes', nameEn: 'Lash Lift', nameAr: 'رفع الرموش', durationMinutes: 45, price: 350, currency: 'AED' },
  { id: 'skin_boost', branchId: 'dubai_main', category: 'Skin', nameEn: 'Skin Booster', nameAr: 'مُعزّز البشرة', durationMinutes: 30, price: 200, currency: 'AED' },

  { id: 'facial_glow', branchId: 'riyadh_center', category: 'Skin', nameEn: 'Glow Facial', nameAr: 'تجميل البشرة', durationMinutes: 60, price: 420, currency: 'SAR' },
  { id: 'body_therapy', branchId: 'riyadh_center', category: 'Body', nameEn: 'Body Therapy', nameAr: 'علاج الجسم', durationMinutes: 90, price: 650, currency: 'SAR' },
  { id: 'brow_design', branchId: 'riyadh_center', category: 'Brows', nameEn: 'Brow Design', nameAr: 'تصميم الحواجب', durationMinutes: 50, price: 320, currency: 'SAR' },
  { id: 'lip_tint', branchId: 'riyadh_center', category: 'Lips', nameEn: 'Lip Tint', nameAr: 'صبغة الشفاه', durationMinutes: 30, price: 220, currency: 'SAR' },

  { id: 'nano_brow', branchId: 'abudhabi_hub', category: 'Brows', nameEn: 'Nano Brow', nameAr: 'الحواجب النانوية', durationMinutes: 90, price: 680, currency: 'AED' },
  { id: 'makeup_edit', branchId: 'abudhabi_hub', category: 'Beauty', nameEn: 'Makeup Edit', nameAr: 'تعديل المكياج', durationMinutes: 45, price: 300, currency: 'AED' },
  { id: 'hydration_mask', branchId: 'abudhabi_hub', category: 'Skin', nameEn: 'Hydration Mask', nameAr: 'قناع الترطيب', durationMinutes: 30, price: 200, currency: 'AED' },
  { id: 'brow_powder', branchId: 'abudhabi_hub', category: 'Brows', nameEn: 'Brow Powder', nameAr: 'مسحوق الحواجب', durationMinutes: 35, price: 240, currency: 'AED' },
];

export const specialists = [
  { id: 'sarah_ali', branchId: 'dubai_main', name: 'Sarah Ali', serviceIds: ['lip_blush', 'brow_lamination', 'lash_lift', 'skin_boost'], timezone: 'Asia/Dubai', schedule: [{ day: 1, start: '09:00', end: '18:00' }, { day: 2, start: '09:00', end: '18:00' }, { day: 3, start: '10:00', end: '19:00' }, { day: 4, start: '09:00', end: '18:00' }, { day: 5, start: '09:00', end: '18:00' }] },
  { id: 'nora_ghani', branchId: 'dubai_main', name: 'Nora Ghani', serviceIds: ['lip_blush', 'skin_boost'], timezone: 'Asia/Dubai', schedule: [{ day: 1, start: '11:00', end: '20:00' }, { day: 2, start: '11:00', end: '20:00' }, { day: 3, start: '11:00', end: '20:00' }, { day: 4, start: '11:00', end: '20:00' }, { day: 5, start: '11:00', end: '20:00' }] },
  { id: 'layla_hamdy', branchId: 'riyadh_center', name: 'Layla Hamdy', serviceIds: ['facial_glow', 'body_therapy', 'brow_design', 'lip_tint'], timezone: 'Asia/Riyadh', schedule: [{ day: 1, start: '09:30', end: '18:30' }, { day: 2, start: '10:00', end: '19:00' }, { day: 3, start: '09:30', end: '18:30' }, { day: 4, start: '09:30', end: '18:30' }] },
  { id: 'mariam_jamal', branchId: 'riyadh_center', name: 'Mariam Jamal', serviceIds: ['brow_design', 'lip_tint'], timezone: 'Asia/Riyadh', schedule: [{ day: 1, start: '12:00', end: '20:00' }, { day: 2, start: '12:00', end: '20:00' }, { day: 4, start: '12:00', end: '20:00' }] },
  { id: 'khalid_saad', branchId: 'abudhabi_hub', name: 'Khalid Saad', serviceIds: ['nano_brow', 'makeup_edit', 'hydration_mask'], timezone: 'Asia/Dubai', schedule: [{ day: 1, start: '10:00', end: '18:00' }, { day: 2, start: '10:00', end: '18:00' }, { day: 3, start: '10:00', end: '18:00' }, { day: 4, start: '10:00', end: '18:00' }, { day: 5, start: '10:00', end: '18:00' }] },
];

export const demoContacts = {
  sarah: {
    id: 'sarah',
    name: 'Sarah',
    language: 'en',
    phone: '+971555123456',
    source: 'qr',
    campaign: 'qr_dubai',
    lastBranchId: 'dubai_main',
    bookings: [
      {
        id: 'GLO-2251',
        branchId: 'dubai_main',
        services: ['lip_blush'],
        specialistId: 'sarah_ali',
        start: '2026-10-02T12:00:00+04:00',
        end: '2026-10-02T13:30:00+04:00',
        status: 'confirmed',
      },
    ],
  },
  new: {
    id: 'new',
    name: 'Guest',
    language: null,
    phone: '',
    source: 'direct',
    campaign: 'spring_booking',
    lastBranchId: null,
    bookings: [],
  },
};

export const demoBookings = [
  {
    id: 'GLO-2251',
    contactId: 'sarah',
    branchId: 'dubai_main',
    serviceIds: ['lip_blush'],
    specialistId: 'sarah_ali',
    start: '2026-10-02T12:00:00+04:00',
    end: '2026-10-02T13:30:00+04:00',
    note: 'Please keep it natural.',
    price: 800,
    currency: 'AED',
    status: 'confirmed',
  },
];

export const demoScenarios = [
  { id: 'new_success', label: 'New customer → success', source: 'direct', contactId: 'new', language: null },
  { id: 'existing_qr', label: 'Existing customer → QR', source: 'qr', contactId: 'sarah', language: 'en' },
  { id: 'no_preference', label: 'No preference specialist', source: 'website', contactId: 'new', language: 'en' },
  { id: 'nogo_branch', label: 'No branch / search fail', source: 'ad', contactId: 'new', language: 'en' },
  { id: 'otp_lock', label: 'Invalid phone + OTP lock', source: 'direct', contactId: 'new', language: 'en' },
  { id: 'hold_expired', label: 'Hold expired', source: 'website', contactId: 'new', language: 'en' },
  { id: 'system_error', label: 'System error then handoff', source: 'ad', contactId: 'new', language: 'en' },
  { id: 'empty_history', label: 'Empty booking history', source: 'direct', contactId: 'new', language: 'en' },
];
